// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDivgproSQiPV1GjznuoOidQjUA03rQENI',
    appId: '1:233536176647:web:c77b6abc8d95fc3e6de0a2',
    messagingSenderId: '233536176647',
    projectId: 'my-barist-app',
    authDomain: 'my-barist-app.firebaseapp.com',
    storageBucket: 'my-barist-app.firebasestorage.app',
    measurementId: 'G-NMXHBEQMSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqyirtkXzzWRSloTt5yZntVir4MdczpbA',
    appId: '1:233536176647:android:b55703b86c9279d46de0a2',
    messagingSenderId: '233536176647',
    projectId: 'my-barist-app',
    storageBucket: 'my-barist-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcyZA2drVRa-eLtTPTWXldBu66BPUDHo',
    appId: '1:233536176647:ios:a4bafd086cd2cc746de0a2',
    messagingSenderId: '233536176647',
    projectId: 'my-barist-app',
    storageBucket: 'my-barist-app.firebasestorage.app',
    iosBundleId: 'com.example.myBaristaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVcyZA2drVRa-eLtTPTWXldBu66BPUDHo',
    appId: '1:233536176647:ios:a4bafd086cd2cc746de0a2',
    messagingSenderId: '233536176647',
    projectId: 'my-barist-app',
    storageBucket: 'my-barist-app.firebasestorage.app',
    iosBundleId: 'com.example.myBaristaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDivgproSQiPV1GjznuoOidQjUA03rQENI',
    appId: '1:233536176647:web:99aa5647838621766de0a2',
    messagingSenderId: '233536176647',
    projectId: 'my-barist-app',
    authDomain: 'my-barist-app.firebaseapp.com',
    storageBucket: 'my-barist-app.firebasestorage.app',
    measurementId: 'G-GVW949XLT9',
  );
}
